### ISSUE TITLE
Need example yaml

### ISSUE THREAD

**Issue by janavenkat** [travisghansen/argo-cd-helmfile#1]
Am not able to achieve your solution. can you please share your example deployment.

Here is my sample deployment

Added these in argocd-cm configmap

```
   configManagementPlugins: |
     - name: helmfile
       init:                         
         command: ["argo-cd-helmfile.sh"]
         args: ["init"]

``` 

Sample app deployment
```
---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "hello-file"
spec:
  project: default
  source:
    repoURL: 'git@github.com:xxo.git'
    path: "argocd-helm/papertrail/test/"
  destination:
    server: ''
    namespace: default
  volumes:
  - name: custom-tools
    emptyDir: {}
  initContainers:
  - name: download-tools
    image: alpine:3.8
    command: [sh, -c]
    args:
      - wget -qO /custom-tools/argo-cd-helmfile.sh https://raw.githubusercontent.com/travisghansen/argo-cd-helmfile/master/src/argo-cd-helmfile.sh &&
        chmod +x /custom-tools/argo-cd-helmfile.sh &&
        wget -qO /custom-tools/helmfile https://github.com/roboll/helmfile/releases/download/v0.98.2/helmfile_linux_amd64 &&
        chmod +x /custom-tools/helmfile
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
  volumeMounts:
  - mountPath: /usr/local/bin/argo-cd-helmfile.sh
    name: custom-tools
    subPath: argo-cd-helmfile.sh
  - mountPath: /usr/local/bin/helmfile
    name: custom-tools
    subPath: helmfile

```

**Comment by travisghansen** [comment]
Thanks for trying it out! You’re approach is slightly off actually. The example provided in the readme is a sample `values.yaml` data for deploying *ArgoCD* itself. Once it is deployed with the init containers etc then you can create an application with the correct definition and it should work. I’ll send a sample application yaml shortly.

**Comment by travisghansen** [comment]
Sample application `source`

```
        source:
          path: monitoring
          plugin:
            env:
            - name: KUBE_VERSION
              value: "1.16"
            - name: HELMFILE_GLOBAL_OPTIONS
              value: --selector name!=kapacitor,name!=elasticsearch,name!=elasticsearch-curator
            name: helmfile
          repoURL: <git url>
          targetRevision: HEAD
```

**Comment by janavenkat** [comment]
> Thanks for trying it out! Your approach is slightly off actually. The example provided in the readme is a sample `values.yaml` data for deploying _ArgoCD_ itself. Once it is deployed with the init containers etc then you can create an application with the correct definition and it should work. I’ll send a sample application yaml shortly.

Thank you

**Comment by travisghansen** [comment]
Yeah, try it out and make sure it works and then I'll close this down :)

**Comment by janavenkat** [comment]
Can please send me your example application that uses helmfile

**Comment by travisghansen** [comment]
Sure:

```
kubectl -n argocd get applications.argoproj.io monitoring -o yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2020-01-09T20:42:22Z"
  generation: 107586
  name: monitoring
  namespace: argocd
  resourceVersion: "177714784"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/monitoring
  uid: d0bf1e98-af73-464f-8da4-e6ab26d35b9d
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: monitoring
    plugin:
      env:
      - name: KUBE_VERSION
        value: "1.16"
      - name: HELMFILE_GLOBAL_OPTIONS
        value: --selector name!=kapacitor,name!=elasticsearch,name!=elasticsearch-curator
      name: helmfile
    repoURL: <repo>
    targetRevision: HEAD
status:
 ...
```

**Comment by janavenkat** [comment]
Am using like this

```
---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "hello-file"
spec:
  project: default
  source:
    repoURL: 'git@github.com:xxx/exx-demo.git'
    path: "argocd-helm/xxx/test"
    plugin:
      env:
      - name: KUBE_VERSION
        value: "1.15"
      name: helmfile
  destination:
    server: 'xxxxxxx'
    namespace: default
```


Argocd-repo-server configured like this

```
 volumes:
  - name: custom-tools
    emptyDir: {}

  initContainers:
  - name: download-tools
    image: alpine:3.8
    command: [sh, -c]
    args:
      - wget -qO /custom-tools/argo-cd-helmfile.sh https://raw.githubusercontent.com/travisghansen/argo-cd-helmfile/master/src/argo-cd-helmfile.sh &&
        chmod +x /custom-tools/argo-cd-helmfile.sh &&
        wget -qO /custom-tools/helmfile https://github.com/roboll/helmfile/releases/download/v0.98.2/helmfile_linux_amd64 &&
        chmod +x /custom-tools/helmfile
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
  volumeMounts:
  - mountPath: /usr/local/bin/argo-cd-helmfile.sh
    name: custom-tools
    subPath: argo-cd-helmfile.sh
  - mountPath: /usr/local/bin/helmfile
    name: custom-tools
    subPath: helmfile
```


and my argocd-cm is

```
    configManagementPlugins: |
      - name: helmfile
        init:         
          command: ["argo-cd-helmfile.sh"]
          args: ["init"]

```

and in my repo am application error like this
![image](https://user-images.githubusercontent.com/28565699/88401848-8bc12400-cdca-11ea-88e0-cab7a28d56ae.png)
