### ISSUE TITLE
Example Helmfile deployments with Argocd

### ISSUE THREAD

**Issue by wajdiail** [travisghansen/argo-cd-helmfile#11]
Hi 

Can you provide an example app deployment using this helmfile plugin in Argocd. How does the app manifest looks like

**Comment by travisghansen** [comment]
Sure, here's a sample of argocd self-managed using the helm-chart:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: raw
    argocd.argoproj.io/instance: argocd
    chart: raw-0.2.5
    heritage: Helm
    release: argocd-apps
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: k8s-services
  source:
    path: .
    plugin:
      env:
      - name: CLUSTER_ID
        value: primary
      - name: HELMFILE_GLOBAL_OPTIONS
        value: --file helmfile.d/applications/argocd/
      - name: HELMFILE_TEMPLATE_OPTIONS
        value: --include-crds
      - name: HELM_TEMPLATE_OPTIONS
        value: --skip-tests
      name: helmfile
    repoURL: https://some/repo/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
```

There is some noise in here but should give you the idea:

```
tree helmfile.d/applications/argocd/
helmfile.d/applications/argocd/
├── 00-argocd.yaml
├── README.md
└── values
    └── argocd
        ├── 00-applicationset.gotmpl
        ├── 00-defaults.gotmpl
        ├── 00-ingress.gotmpl
        ├── 01-apps.gotmpl
        ├── static
        │   ├── app-projects.yaml
        │   ├── argocd-age-secret-keys-sealed-secret.yaml
        │   └── argocd-repository-credentials-sealed-secret.yaml
        └── static.gotmpl
```

The `00-argocd.yaml` file looks like this:

```
---
bases:
- ../../bases/repositories.yaml
- ../../bases/environments.yaml.gotmpl
- ../../bases/api-versions.yaml

# https://github.com/roboll/helmfile/issues/1230
---
releases:

# https://github.com/helm/charts/tree/master/incubator/raw
- name: argocd-static
  installed: {{ .Values.releases.argocd.installed }}
  chart: incubator/raw
  values:
  - ./values/argocd/static.gotmpl

- name: argocd-ingress
  #installed: {{ .Values.releases.argocd.installed }}
  # not installing for now due to going through haproxy etc
  installed: false
  chart: incubator/raw
  values:
  - ./values/argocd/00-ingress.gotmpl

# https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#declarative-setup
# https://argoproj.github.io/argo-cd/user-guide/diffing/
# https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd
# https://itnext.io/argocd-a-helm-chart-deployment-and-working-with-helm-secrets-via-aws-kms-96509bfc5eb3
- name: argocd
  installed: {{ .Values.releases.argocd.installed }}
  chart: {{ .Values.releases.argocd.chart }}
  version: {{ .Values.releases.argocd.version }}
  values:
  - ./values/argocd/00-defaults.gotmpl
{{- if .Values.releases.argocd.values }}
{{ .Values.releases.argocd.values | toYaml | indent 2 }}
{{- end }}

- name: argocd-applicationset
  installed: {{ .Values.releases.argocd.installed }}
  chart: {{ .Values.releases.argocdApplicationset.chart }}
  version: {{ .Values.releases.argocdApplicationset.version }}
  values:
  - ./values/argocd/00-applicationset.gotmpl

- name: argocd-apps
  installed: {{ .Values.releases.argocd.installed }}
  chart: incubator/raw
  values:
  - ./values/argocd/01-apps.gotmpl

```

Does that help?

**Comment by nweiler** [comment]
@travisghansen Would you be willing to post a full code example of an app deployment using the helmfile plugin? I'm still a bit confused as to what the whole thing should supposed to look like. Thanks!

**Comment by travisghansen** [comment]
Sure! `CLUSER_ID` and `ENVIRONMENT_ID` are specific to my helfiles, the rest is generic functionality that should be familiar to those with experience using `helmfile`...

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-workload-00-velero
  namespace: argocd
spec:
  destination:
    name: dev-workload-00
    namespace: velero
  project: k8s-services
  source:
    path: .
    plugin:
      env:
      - name: CLUSTER_ID
        value: workload-00
      - name: ENVIRONMENT_ID
        value: dev
      - name: HELMFILE_GLOBAL_OPTIONS
        value: --file helmfile.d/applications/velero/ --selector argoEnabled=true,argoApplication=velero
      - name: HELMFILE_TEMPLATE_OPTIONS
        value: --include-crds
      - name: HELM_TEMPLATE_OPTIONS
        value: --skip-tests
      name: helmfile
    repoURL: https://.../k8s-services.git
    targetRevision: HEAD
```
