### ISSUE TITLE
Helm secrets support

### ISSUE THREAD

**Issue by kfirfer** [travisghansen/argo-cd-helmfile#20]
Hello,

I have setup helm secrets in ArgoCD following this guide:
https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration

And also installed helmfile plugin in ArgoCD

And I couldn't use helm secrets

Example helmfile:
```
repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
  - name: homer
    version: 7.2.2
    chart: k8s-at-home/homer
    namespace: homer
    values:
      - values.yaml
    secrets:
      - values-secrets.yaml
#      - secrets+gpg-import:///helm-secrets-private-keys/key.asc?values-secrets.yaml

```

Argo app:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: homer-helmfiles
  namespace: argocd
spec:
  destination:
    namespace: homer
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: nucs/dev/us-east/apps/namespaces/homer/helmfile
    plugin:
      name: helmfile
    repoURL: https://<mygit>.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true

```

In `nucs/dev/us-east/apps/namespaces/homer/helmfile` :
```
.sops.yaml
helmfile.yaml - the file above
values.yaml
values-secrets.yaml - encrypted with helm secrets
```

Everything works as intended without using the secrets

**Comment by travisghansen** [comment]
I doubt the custom integration would work with helmfile directly. In my case I use `age` with centrally managed keys which are published throughout the organization (each cluster has numerous keys available to it, a global key, a cluster key, an env key, etc). To make it all work it requires:

```
# set env on repo server
  - name: SOPS_AGE_KEY_FILE
    value: /sops/age/keys.txt

# volume for repo server
  - name: age-secret-keys
    secret:
      secretName: argocd-age-secret-keys

# volume mount for repo server
  - mountPath: /sops/age
    name: age-secret-keys

# create the secret
apiVersion: v1
kind: Secret
metadata:
  name: argocd-age-secret-keys
  namespace: argocd
stringData:
  keys.txt: |
    # place all keys here
```
