### ISSUE TITLE
Support for ArgoCD v2.5.1

### ISSUE THREAD

**Issue by Coder63** [travisghansen/argo-cd-helmfile#30]
Do you expect this to work as sidecar option too ?  With v2.5.1 configmap is deprecated . Any pointer to make it work for sidecar option ...

**Comment by travisghansen** [comment]
It has been on my list to look into what the new interface is but I haven’t had a chance :( I do intend to make update to the newer style when I can however.

**Comment by joshuasimon-taulia** [comment]
Maybe https://github.com/lucj/argocd-helmfile-plugin should be consolidated with this project

**Comment by Coder63** [comment]
@joshuasimon-taulia : Did it work for you ?  It did not work for me and says WIP too

**Comment by Coder63** [comment]
> Maybe https://github.com/lucj/argocd-helmfile-plugin should be consolidated with this project

@joshuasimon-taulia : Did it work for you ? It did not work for me and says WIP too

**Comment by joshuasimon-taulia** [comment]
haven't tried it yet. it just seems like duplicate effort

**Comment by travisghansen** [comment]
I'm happy to collaborate. He never reached out unfortunately :(

**Comment by lucj** [comment]
Hi @joshuasimon-taulia did you try my repo but did not managed to have it working fine ?
@travisghansen I would be happy to collaborate 👍

**Comment by travisghansen** [comment]
@lucj I think that would be great! I haven’t had time to investigate the sidecar approach yet and likely will be another couple of weeks before I can really dig in (time consuming life events going on atm). If it makes sense we could fire up a new github org and formalize things a bit more.

**Comment by lucj** [comment]
@travisghansen no problem at all. In the meantime I'll update the instructions a bit so it's easier to give it a try. 
My repo is currently a WIP so that will make sense to formalize the things later on, totally agree on that.

**Comment by lucj** [comment]
Thanks @armenr for this feedback. Could you tell me more regarding the tweak ?

**Comment by samba1112** [comment]
Any update on updating Documentation for sidecar method with Argocd helm values

**Comment by travisghansen** [comment]
OK, finally have some time to look into this. @lucj you want to sync up and collaborate at all?

**Comment by travisghansen** [comment]
OK team, I have build images of this now so you should be able to try it as the sidecar setup (I haven't ran it yet personally but probably will try in the next week or so). For anyone wanting to give it a go it should be pretty simple:

```
containers:
- name: cmp
  image: travisghansen/argo-cd-helmfile:latest
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
  volumeMounts:
    - mountPath: /var/run/argocd
      name: var-files
    - mountPath: /home/argocd/cmp-server/plugins
      name: plugins
    # mitigate path traversal attacks.
    - mountPath: /tmp
      name: cmp-tmp
volumes:
  - emptyDir: {}
    name: cmp-tmp
```

I would recommend adding any custom tools via the init process into the/a shared dir and then setting the `PATH` `env` of the container to something like:

```
PATH=/custom-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

The discovery process has been implemented so it should pick that up ok. Generally following the instructions here should get you going: https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#3-register-the-plugin-sidecar
