### ISSUE TITLE
Private OCI repositories

### ISSUE THREAD

**Issue by kfirfer** [travisghansen/argo-cd-helmfile#33]
Hello

for somehow, helmfile plugin getting authentication error while pulling charts from private OCI registries like dockerhub

I had an workaround, to put this init script (HELMFILE_INIT_SCRIPT_FILE)

`echo "echo \$HELM_REPOSITORY_PASSWORD | helm registry login registry-1.docker.io -u \$HELM_REPOSITORY_USERNAME --password-stdin" > init_auth.sh`

**Comment by travisghansen** [comment]
Can you share what the error is? What were you doing to set the creds previously vs the init script?

**Comment by travisghansen** [comment]
Can you use the syntax mentioned here: https://helmfile.readthedocs.io/en/latest/#configuration

```yaml
# to use repositories other than the official repository or one backend by chartmuseum.
repositories:
# Advanced configuration: You can setup basic or tls auth and optionally enable helm OCI integration
- name: roboll
  url: roboll.io/charts
  certFile: optional_client_cert
  keyFile: optional_client_key
  # username is retrieve from the environment with the format <registryNameUpperCase>_USERNAME for CI usage, here ROBOLL_USERNAME
  username: optional_username
  # username is retrieve from the environment with the format <registryNameUpperCase>_PASSWORD for CI usage, here ROBOLL_PASSWORD
  password: optional_password
  oci: true
  passCredentials: true
```
