### ISSUE TITLE
helmfile/vals integration

### ISSUE THREAD

**Issue by crabique** [travisghansen/argo-cd-helmfile#42]
Hello,

Is it possible to enable the https://github.com/helmfile/vals templating pass during the manifests render so that external values can be used as well?

**Comment by travisghansen** [comment]
Never used it but looks cool. The idea would be to the entire output through vals as a post processing pass?

**Comment by travisghansen** [comment]
https://github.com/travisghansen/argo-cd-helmfile/blob/master/src/argo-cd-helmfile.sh#L406

**Comment by crabique** [comment]
Yes, in my specific use case I'm interested in fetching data directly from terraform statefile on an S3 bucket into the environment helmfile so it's available as a `.StateValue`, but it seems there's no real difference as the processing can only happen after helmfile template output.

**Comment by travisghansen** [comment]
Yeah, so basically all we need to do would be something like this:

```
  export HELMFILE_POST_PROCESS=" | vals eval -f - "

    ${helmfile} \
      template \
      --skip-deps ${INTERNAL_HELMFILE_TEMPLATE_OPTIONS} \
      --args "${INTERNAL_HELM_TEMPLATE_OPTIONS} ${HELM_TEMPLATE_OPTIONS}" \
      ${HELMFILE_TEMPLATE_OPTIONS} ${HELMFILE_POST_PROCESS}
    ;;
```

**Comment by travisghansen** [comment]
From what I can tell `helmfile` already has support for this built-in. My testing shows the refs/values being rendered without even installing the `vals` binary independently.

**Comment by crabique** [comment]
Oh my, you are right, I just searched their documentation by `ref` keyword and found this: https://helmfile.readthedocs.io/en/latest/remote-secrets/

Sorry 😄 

Thanks for the very quick response!

**Comment by travisghansen** [comment]
I didn't even read that, but this works as well:

```
# both syntaxes below work for me
releases:
- name: grafana
  namespace: monitoring
  chart: stable/grafana
  set:
  - name: adminPassword
    value: ref+envsubst://$VAR1
  ...
  values:
  - adminPassword: ref+envsubst://$VAR1

```
