### ISSUE TITLE
Integrated ArgoCD plugin parameters support ?

### ISSUE THREAD

**Issue by christiansen-merel** [travisghansen/argo-cd-helmfile#50]
Hello.
First, thanks for the great work.

Is there a plan to support plugin parameters in Application scope ? [here in documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#using-environment-variables-in-your-plugin)

For the example case from the ArgocD documentation:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    plugin:
      parameters:
        - name: FOO
          value: bar
        - name: REV
          value: test-$ARGOCD_APP_REVISION
```
The plugin would add `--state-values-set FOO=bar --state-values-set REV=test-$ARGOCD_APP_REVISION` to the helmfile command.

It could also use `--state-values-file` if the parameter value appears to be a file. It could fix issue #46 if I understand it well.

Does it makes sense ?

I might submit a PR if interrested.

**Comment by christiansen-merel** [comment]
Juste read the CMP Proposal I previously missed.

I guess it could be better to add only a `values` parameter that mimic the helmfile release.values parameter. 
This feature would be valuable for ApplicationSet especially.

Usage example:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
...
    plugin:
      parameters:
        - name: values
          array:
            - values-as-file.yaml
            - anotherValueAsObjet:
                attributeOne: foo
                attributeTwo: bar
```
