### ISSUE TITLE
kubectl context support

### ISSUE THREAD

**Issue by vquie** [travisghansen/argo-cd-helmfile#59]
Hi,

we are evaluating ArgoCD in our company where we use a lot of helmfile already. Hense this plugin is our saviour. :-)
We use a lot of hooks where we fetch data from the cluster with kubectl. It works like a charm when deploying to the cluster ArgoCD runs on but does not when working with multiple clusters. It seems that there is no actual context in kubeconfig. 

I managed to exec this stupid bash script to add the content as annotation in my deployment.

```bash
#!/bin/bash

_CONFIG=$(kubectl config view | base64)

echo "${_CONFIG}"

```

It shows this:
```yaml
apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null
```

What am I missing?

ArgoCD version: v2.10.0
argo-cd-helmfile: v0.3.9

Thank you very much!
