### ISSUE TITLE
Pass helm values from separate repo

### ISSUE THREAD

**Issue by chanakya-svt** [travisghansen/argo-cd-helmfile#60]
Having trouble passing the helm values from one repository to another.

I have the following `helmfile.yaml` in `some-repo-a`
```yaml
bases:
  - ../../../bases/helm-defaults.yaml
missingFileHandler: Error
releases:
  - name: "namespaces"
    namespace: "default"
    createNamespace: true
    chart: "../../../charts/namespaces"
    values:
      - {{ env "ARGOCD_ENV_NAMESPACES_VALUES_FILE" | quote }}
```

I have the following ArgoCD Application config in `some-repo-b`
```yaml
spec:
      project: default
      sources:
        - repoURL: "https://github.com/some-repo-a"
          path: "src"
          targetRevision: "main"
          plugin:
            name: "helmfile"
            env:
              - name: "NAMESPACES_VALUES_FILE"
                value: $values/path/to/values.yaml
        - repoURL: "https://github.com/some-repo-b"
          targetRevision: main
          ref: values
     destination:
        server: "in-cluster"
        namespace: "default"
```

I configured the ArgoCD RepoServer following [this guide](https://christianhuth.de/deploying-helm-charts-using-argocd-and-helmfile/)

When I try to sync the application I am getting `/path/to/values.yaml file or directory does not exists`. 

Is there a way to pass the values yaml from a different repository like the above setup.
