### ISSUE TITLE
having environment files in another directory and to be pulled in init phase

### ISSUE THREAD

**Issue by abdennour** [travisghansen/argo-cd-helmfile#7]
Hello ,
I have this repo structure

```
git-repo
|___ scripts/
|       |___ vault-pull
|___ environments/
|       |___ prod.yaml
|       |___ dev.yaml
|
|___app-1/
|       |___ helmfile.yaml
|       |___ values.yaml.gotmpl
|
|___app-2/
|       |___ helmfile.yaml
|       |___ values.yaml.gotmpl
```

The content of any helmfile starts by importing the environment files : 

```yaml
# app-x/helmfile.yaml content
# ...
environments:
  dev:
    values:
    - ../environments/dev.yaml
  prod:
    values:
    - ../environments/prod.yaml
releases: 
#......
```

- The first challenge is "environments/" directory is not in the same directory of helmfile. However it's accessible relatively within the same git repo.

- The second challenge is "environments/" is in .gitignore, and i have to run script (scripts/vault-pull) in "init" phase in order to pull environment files.

To move forward, i customized this plugin : 

```sh

  "init")
   # ...
      if [ ! -z "${HELMFILE_INIT_SCRIPT_FILE}" ]; then 
          bash "${HELMFILE_INIT_SCRIPT_FILE}"
      fi

```

in the argo app, i configure it like this : 

```yaml
kind: Application
metadata:
  name: app-2
# ....
spec:
  source:
    path: app-1
    repoURL: 'https://bitbucket.org/example/git-repo.git'
    targetRevision: HEAD
    plugin:
      name: helmfile
      env:
      - name: HELMFILE_INIT_SCRIPT_FILE
        value: ../scripts/vault-pull
```

However, the app is not deployed and i can see an error saying that file `../scripts/vault-pull` is not found/not exist.

What's issue ? does this plugin process things outside the git repo ?
