### ISSUE TITLE
Not sure how to put the environment variable flag in helmfile

### ISSUE THREAD

**Issue by cwusyscrest** [travisghansen/argo-cd-helmfile#9]
Hi,

Thank you for developing such a great plugin for helmfile. I was wondering what I did wrong if I want to achieve something like `helmfile --environment development apply`. 

Here is my application manifest:
```
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: {{ .Values.spec.source.path }}
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    plugin:
      name: helmfile
      env:
      - name: HELMFILE_GLOBAL_OPTIONS
        value: '"--environment development"'
    helm:
      # Release name override (defaults to application name)
      releaseName: guestbook-{{ .Values.environment }}

      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      valueFiles:
        - values-{{ .Values.environment }}.yaml
```
Here is structure of the example project:

![Screenshot 2021-03-26 at 14 51 17](https://user-images.githubusercontent.com/81158123/112641570-c93aed00-8e42-11eb-9d4e-bbb675812349.png)

So basically what I want to achieve here is that I want to specify `--environment` in order to tell helmfile which values.yaml to take when rendering the manifest. Thank you!
